#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username ${POSTGRES_USER} --dbname postgres <<-EOSQL
  DO \$createuser\$
  BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${AUTHENTIK_POSTGRESQL__USER}') THEN
      CREATE ROLE ${AUTHENTIK_POSTGRESQL__USER} WITH LOGIN;
    END IF;
  END \$createuser\$;

  ALTER USER ${AUTHENTIK_POSTGRESQL__USER} WITH PASSWORD '${AUTHENTIK_POSTGRESQL__PASSWORD}';
  CREATE DATABASE IF NOT EXISTS ${AUTHENTIK_POSTGRESQL__NAME} WITH OWNER ${AUTHENTIK_POSTGRESQL__USER};
  GRANT ALL PRIVILEGES ON DATABASE ${AUTHENTIK_POSTGRESQL__NAME} TO ${AUTHENTIK_POSTGRESQL__USER};
EOSQL
